//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Logistika
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч своб мест.
    /// </summary>
    // *** Start programmer edit section *** (ТЧСвобМест CustomAttributes)

    // *** End programmer edit section *** (ТЧСвобМест CustomAttributes)
    [AutoAltered()]
    [Caption("Свободное место")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧСвобМестE", new string[] {
            "ЗагрузКонтейн as \'Номер документа загрузки контейнеров\'",
            "ЗагрузКонтейн.НомерДокЗагк as \'Номер документа загрузки контейнеров\'",
            "ЗагрузКонтейн.Контейнеры.НомерКонтей as \'Номер контейнера\'",
            "ЗагрузКонтейн.Контейнеры.Объем as \'Объем контейнера, м^3\'",
            "СвобОбъем as \'Освободившийся объем, м^3\'"}, Hidden=new string[] {
            "ЗагрузКонтейн.НомерДокЗагк"})]
    [MasterViewDefineAttribute("ТЧСвобМестE", "ЗагрузКонтейн", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерДокЗагк")]
    public class ТЧСвобМест : ICSSoft.STORMNET.DataObject
    {
        
        private double fСвобОбъем;
        
        private IIS.Logistika.ЗагрузКонтейн fЗагрузКонтейн;
        
        private IIS.Logistika.ДокумРезультП fДокумРезультП;
        
        // *** Start programmer edit section *** (ТЧСвобМест CustomMembers)

        // *** End programmer edit section *** (ТЧСвобМест CustomMembers)

        
        /// <summary>
        /// СвобОбъем.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСвобМест.СвобОбъем CustomAttributes)

        // *** End programmer edit section *** (ТЧСвобМест.СвобОбъем CustomAttributes)
        public virtual double СвобОбъем
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСвобМест.СвобОбъем Get start)

                // *** End programmer edit section *** (ТЧСвобМест.СвобОбъем Get start)
                double result = this.fСвобОбъем;
                // *** Start programmer edit section *** (ТЧСвобМест.СвобОбъем Get end)

                // *** End programmer edit section *** (ТЧСвобМест.СвобОбъем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСвобМест.СвобОбъем Set start)

                // *** End programmer edit section *** (ТЧСвобМест.СвобОбъем Set start)
                this.fСвобОбъем = value;
                // *** Start programmer edit section *** (ТЧСвобМест.СвобОбъем Set end)

                // *** End programmer edit section *** (ТЧСвобМест.СвобОбъем Set end)
            }
        }
        
        /// <summary>
        /// Т ч своб мест.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСвобМест.ЗагрузКонтейн CustomAttributes)

        // *** End programmer edit section *** (ТЧСвобМест.ЗагрузКонтейн CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗагрузКонтейн"})]
        [NotNull()]
        public virtual IIS.Logistika.ЗагрузКонтейн ЗагрузКонтейн
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСвобМест.ЗагрузКонтейн Get start)

                // *** End programmer edit section *** (ТЧСвобМест.ЗагрузКонтейн Get start)
                IIS.Logistika.ЗагрузКонтейн result = this.fЗагрузКонтейн;
                // *** Start programmer edit section *** (ТЧСвобМест.ЗагрузКонтейн Get end)

                // *** End programmer edit section *** (ТЧСвобМест.ЗагрузКонтейн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСвобМест.ЗагрузКонтейн Set start)

                // *** End programmer edit section *** (ТЧСвобМест.ЗагрузКонтейн Set start)
                this.fЗагрузКонтейн = value;
                // *** Start programmer edit section *** (ТЧСвобМест.ЗагрузКонтейн Set end)

                // *** End programmer edit section *** (ТЧСвобМест.ЗагрузКонтейн Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Logistika.ДокумРезультП.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСвобМест.ДокумРезультП CustomAttributes)

        // *** End programmer edit section *** (ТЧСвобМест.ДокумРезультП CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ДокумРезультП"})]
        public virtual IIS.Logistika.ДокумРезультП ДокумРезультП
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСвобМест.ДокумРезультП Get start)

                // *** End programmer edit section *** (ТЧСвобМест.ДокумРезультП Get start)
                IIS.Logistika.ДокумРезультП result = this.fДокумРезультП;
                // *** Start programmer edit section *** (ТЧСвобМест.ДокумРезультП Get end)

                // *** End programmer edit section *** (ТЧСвобМест.ДокумРезультП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСвобМест.ДокумРезультП Set start)

                // *** End programmer edit section *** (ТЧСвобМест.ДокумРезультП Set start)
                this.fДокумРезультП = value;
                // *** Start programmer edit section *** (ТЧСвобМест.ДокумРезультП Set end)

                // *** End programmer edit section *** (ТЧСвобМест.ДокумРезультП Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧСвобМестE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСвобМестE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСвобМестE", typeof(IIS.Logistika.ТЧСвобМест));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧСвобМест.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧСвобМест CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧСвобМест CustomAttributes)
    public class DetailArrayOfТЧСвобМест : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Logistika.DetailArrayOfТЧСвобМест members)

        // *** End programmer edit section *** (IIS.Logistika.DetailArrayOfТЧСвобМест members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧСвобМест by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧСвобМест.
        /// </summary>
        public DetailArrayOfТЧСвобМест(IIS.Logistika.ДокумРезультП fДокумРезультП) : 
                base(typeof(ТЧСвобМест), ((ICSSoft.STORMNET.DataObject)(fДокумРезультП)))
        {
        }
        
        public IIS.Logistika.ТЧСвобМест this[int index]
        {
            get
            {
                return ((IIS.Logistika.ТЧСвобМест)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Logistika.ТЧСвобМест dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
